language: node_js
node_js:
- 6
install:
- npm install
- npm link
deploy:
  skip_cleanup: true
  provider: npm
  email: bradwoo8621@gmail.com
  api_key:
    secure: xWdByRjzmsJ9zhEMDrtb73kClgtu69wTvT+pZ/ZRDY4uZwwD6vczjK5TGPHtbbG5ZCK7iBwXH5WKcz/QHjpH9jwMpyb4QkcRUj2DJswiarDdPz8OGDS1WEWO9XR2ZbFuK7XdHtRtQYauvQ/C1f6txp6W8xZIJPkb7wmlSzMvNXYh3cnnLl6TBCxUBI/syJJliLax2iYivsMM2mzYFYG0zZeMO4yQq58SoSv06H3/K7Y7VxII0mno6eUYDc9+j3t7VYgQpdibdXLcEwMK9eYtpOixScQQnKJN8nzkv9/3JjdfLjixfi1ZeufgjpJydFXdQjQm4JWUWf8l1bZjoSYoS08PUGWjM2oCHByYJ1YT788ZWGuwz42pe7Vjp7UbOW5mDPzwq79v6fiWZtN3bw5zMbK7X+lQuzUD9ynOc8xVENCJg7mfwKgKZ7v3Ku47IePAjQEPxZ+egF9JzdrGEp006q4QhE5fvfai5sDd7kEaBNVoUVqYpRxCjVAcjJh8zjv2IFcsQN3/Yj2rddf2DSDL4DMvpJaRB68gv6IKANLY0/rCXSRFUVW61YxbBLW8pb/6twt06AvPnyEtrnjVdo23ZUBtTvKdwr7y720+KqE5/gCra+l6oIKRw1GqDxFQAGklWDzBVyFy9Cg+3b+LvliT2Hl2m2FD8nj76baZ+wpfmVI=
  on:
    tags: true
