language: node_js
node_js:
- 6
install:
- npm install
- npm link
deploy:
  skip_cleanup: true
  provider: npm
  email: bradwoo8621@gmail.com
  api_key:
    secure: YMd7KlsE5xknWZ+lodDAZ6WIu0hwOYswwIxe3X9UkzH3Z0TytyVq9sFQ3enfBU2ot6T4K20RKGp9HIYLJ37D5GwLthW1OSBtX/srMpBJ5+AnM7sx1o8h7UYLFp1HyXey4X79ER6N3ItrgE/QAJAURMY5oiT7bLz5MYBuVDtEvVRZviMD2JXO0WgHtYGR2pAJlr5xwUAdH5gCW25MvPT27dyhNmbzoCiXO7tu8Ny4EG13DY1PWdVdmEQh/yPi/k5L8f9kxCGKoOgEYk3A3AZYTvi4YzK+SndoAGlebP9KqMKaIQPuEb5UQmXcSB+8nj6uNU9Bw3GSUZNGP3g3aStWkCiAGNZCpY7jyupuorQlhpWrtNaTAD7R4k6Honu/BWr0orbHZq+0i3S6X71/b5nkATvVl/OsODwOqpLn1oDaNA4FcaqzmZNDLqmeTH2G5iJjhZgKZjZpYSrB5xZw32rVMXk8Ndg4uNG5mEGxqlvgk0pGEr4A60WL8Pb5DhCB2ykp5Ja+23QLfZ47Gh/uf2/WzzwsGK2VbrXnWR9IGRUwjvRuQ0Cp572+a+cKk/ga2bpFrIP/yAu+kABjJRhpNBMHvxQIcuAF+e8j1Y4XaaRYp9VRMsjesJKLOIpbwEs8bv7357zvO4feGoAvSgssZhWrdiNFXDnn52DES0/wF7aYs/g=
  on:
    tags: true
