language: node_js
node_js:
- 6
install:
- npm install
- npm link
deploy:
  skip_cleanup: true
  provider: npm
  email: bradwoo8621@gmail.com
  api_key:
    secure: HtisBaxPHq1KKTYUniIls2xtzX5SZVUV19iR3XdRkyfAun+soPvP7JQ+iThb9WtGlxYrOh00m0so1B1lBsy3pNcVxfqbdlo/5PZvP1fuRD9nJ45lXA9MIE/2VztRRRDcJhhfeqgN48yBsjPybNL7Jq9zp9wwAWK9n0PUjypssfb1B8scJ8TaxMICdtnKxlF+DEVrxBgUnDO9V/0kHn8d5T9WgkRXu1jCK8FVPk+OiijH/mYj219loyu+MZ55RSQNsiSS/sMCMx7+FhwkTfCOFoGvf9M4zsJ+7FL2JM1nmeGtgEn7PqUZFx1+tR9WCbg65w0D8042Hj5yNv9PTs4II9bq9kdMyDniD0+z3j96HI20DFX2GFOcvTJ9SICwmKU1kuXrEXSisFt8D+jduNrw1rZ3Li7JCEKAZy/GAonJ5qP+lrg9k4GPENiF26crdwnkdb4/9d1i6ITnu/fwvWbY3H9jHIPwlHEgUHHu8nSl2q9cmSwDo3eFdhw/j4s7Mb7nW/9Op6Uh3gagr9VttRrM8J/uE4mi2sCZiSK9lRZ4zRa95fG+TRARhKino7IuhE96HifXETekUGLjfATQoBNUAGCH6NtJBnt17cn7OkgN3YCIhJ0iANCt2+3D0NPaKNAgMZheqWPaJwINDRmwg9FnI7hILV4xy/1ogjKyHwBkdhE=
  on:
    tags: true
